# 1. Foundations

## What is Pandas?
Pandas is an open-source Python library built for data manipulation and analysis. It provides fast, flexible, and expressive data structures designed to work with structured (tabular) and time-series data. It is built on top of NumPy.

## Installation & Import

#### Install via conda
conda install pandas

In [12]:
import pandas as pd

## Core Data Structures

There are two main data structures in pandas viz.

### (A) Series
A Series is a one-dimensional labeled array that can hold any data type (integers, strings, floats, Python objects, etc.). Think of it as a single column in a spreadsheet.

### Creating a Series

In [34]:
series_1=pd.Series([10,20,30,40,50,60])
series_1

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

### Series with custom index

In [35]:
series_2 = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
series_2

a    10
b    20
c    30
dtype: int64

### Series from a dictionary

In [33]:
series_3 = pd.Series({'name': 'Sarthak', 'age': 20, 'city': 'Mumbai'})
series_3

name    Sarthak
age          20
city     Mumbai
dtype: object

### Accessing elements

In [32]:
# label-based
print(series_3['age']) 
print(series_2['c']) 

 # position-based
series_1[0]

20
30

np.int64(10)

### (B) DataFrame
A DataFrame is a two-dimensional labeled data structure with columns of potentially different types. Think of it as a full spreadsheet or SQL table. It is the most commonly used pandas object.

### Creating a DataFrame from a dictionary

In [31]:
df_1 = pd.DataFrame({
'name':  ['Alice', 'Bob', 'Charlie'],
'age':   [25, 30, 35],
'score': [88.5, 92.0, 78.3]
})
df_1

      name  age  score
0    Alice   25   88.5
1      Bob   30   92.0
2  Charlie   35   78.3

### From a list of dictionaries

In [30]:
data = [{'name': 'Alice', 'age': 25}, {'name': 'Bob', 'age': 30}]
df_2 = pd.DataFrame(data)
df_2

    name  age
0  Alice   25
1    Bob   30

### From a CSV file

In [47]:
order_data = pd.read_csv('orders.csv')
order_data

    order_id    product     category    price delivered
0       1001      Phone  Electronics  15000.0       Yes
1       1002    T-Shirt     Clothing    499.0       Yes
2       1003     Laptop  Electronics  55000.0       Yes
3       1004       Rice      Grocery    120.0       Yes
4       1005      Jeans     Clothing   1200.0        No
5       1006  Earphones  Electronics    999.0       Yes
6       1007      Dress     Clothing   1899.0       Yes
7       1008     Tablet  Electronics  22000.0        No
8       1009      Sugar      Grocery     50.0       Yes
9       1010      Kurti     Clothing    799.0       Yes
10      1011      Phone  Electronics  12000.0       Yes
11      1012        Oil      Grocery    180.0       Yes
12      1013     Laptop  Electronics      NaN       Yes
13      1014      Jeans     Clothing   1500.0        No
14      1015       Rice      Grocery    120.0       Yes

### Exporting Dataframes

In [48]:
order_data.to_csv("indexed-exported-orders.csv")

When pandas saves a DataFrame to CSV, it automatically adds an extra column at the start for the row numbers (0, 1, 2, 3...),that's the index.So we write "index=False" to avoid getting the first unnamed column. So "index=False" simply means "don't write the row numbers into the file". You'll use this almost every time you export a CSV.

In [49]:
order_data.to_csv("unindexed-exported-orders.csv", index=False)

# 2. Data Inspection
Before working with any dataset, always inspect it first to understand its structure, size, and data types.

## Common Pandas Methods

### (A) .head()
.head() displays the first 5 rows of a pandas DataFrame or Series to quickly preview the data

In [53]:
order_data.head()

   order_id  product     category    price delivered
0      1001    Phone  Electronics  15000.0       Yes
1      1002  T-Shirt     Clothing    499.0       Yes
2      1003   Laptop  Electronics  55000.0       Yes
3      1004     Rice      Grocery    120.0       Yes
4      1005    Jeans     Clothing   1200.0        No

If you want to view a specific number of rows, you can add the number inside the parentheses of .head(), and it will display that many rows

In [54]:
order_data.head(8)

   order_id    product     category    price delivered
0      1001      Phone  Electronics  15000.0       Yes
1      1002    T-Shirt     Clothing    499.0       Yes
2      1003     Laptop  Electronics  55000.0       Yes
3      1004       Rice      Grocery    120.0       Yes
4      1005      Jeans     Clothing   1200.0        No
5      1006  Earphones  Electronics    999.0       Yes
6      1007      Dress     Clothing   1899.0       Yes
7      1008     Tablet  Electronics  22000.0        No

### (B) .tail()
.tail() displays the last 5 rows of a pandas DataFrame or Series to quickly view the end of the data

In [55]:
order_data.tail()

    order_id product     category    price delivered
10      1011   Phone  Electronics  12000.0       Yes
11      1012     Oil      Grocery    180.0       Yes
12      1013  Laptop  Electronics      NaN       Yes
13      1014   Jeans     Clothing   1500.0        No
14      1015    Rice      Grocery    120.0       Yes

Similar to .head(), if you want a specific number of rows, you can add the number inside the parentheses

In [58]:
order_data.tail(7)

    order_id product     category    price delivered
8       1009   Sugar      Grocery     50.0       Yes
9       1010   Kurti     Clothing    799.0       Yes
10      1011   Phone  Electronics  12000.0       Yes
11      1012     Oil      Grocery    180.0       Yes
12      1013  Laptop  Electronics      NaN       Yes
13      1014   Jeans     Clothing   1500.0        No
14      1015    Rice      Grocery    120.0       Yes

### (C) .info()
.info() is a pandas method that displays a summary of a DataFrame.

It shows:

number of rows

column names

non-null values

data types of each column

memory usage

In [61]:
order_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   order_id   15 non-null     int64
 1   product    15 non-null     str
 2   category   15 non-null     str
 3   price      14 non-null     float64
 4   delivered  15 non-null     str
dtypes: float64(1), int64(1), str(3)
memory usage: 732.0 bytes

We use .info() to get a quick summary of the dataset’s structure, data types, and missing values