# MODULE 1 : Welcome to Pandas

## [🟢] Level 1 : Foundations

## Problem 1

> Install Pandas using pip and verify the installation by displaying the installed Pandas version.

In [3]:
pip install pandas

Requirement already satisfied: pandas in C:\Users\sarthak\miniconda3\envs\ml-ai-env\Lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\sarthak\miniconda3\envs\ml-ai-env\Lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\sarthak\miniconda3\envs\ml-ai-env\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\sarthak\miniconda3\envs\ml-ai-env\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\sarthak\miniconda3\envs\ml-ai-env\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
pip show pandas

Name: pandas
Version: 3.0.1
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author:
Author-email: The Pandas Development Team <pandas-dev@python.org>
License: BSD 3-Clause License

 Copyright (c) 2008-2011, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team
 All rights reserved.

 Copyright (c) 2011-2026, Open source contributors.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

 * Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Location: C:\Users\sarthak\miniconda3\envs\ml-ai-env\Lib\site-packages
Requires: numpy, python-dateutil, tzdata
Required-by:
Note: you may need to restart the kernel to use updated packages.

## Problem 2

> Import Pandas using the conventional alias `pd`.

In [5]:
import pandas as pd

## Problem 3

> Create a Series containing the names of five cities you'd love to visit.

In [6]:
dream_cities=pd.Series(["Tokyo","Paris", "New York","London","Sydney"])
dream_cities

0       Tokyo
1       Paris
2    New York
3      London
4      Sydney
dtype: str

## Problem 4

> Create a Series containing the numbers `10, 20, 30, 40, 50`.

In [7]:
num_series=pd.Series([10,20,30,40,50])
num_series

0    10
1    20
2    30
3    40
4    50
dtype: int64

## Problem 5

> Display the first three elements of your cities Series.

In [8]:
dream_cities[:3]

0       Tokyo
1       Paris
2    New York
dtype: str

## Problem 6

> Display the last two elements of your numbers Series.

In [9]:
num_series[-2:]

3    40
4    50
dtype: int64

## Problem 7

> Create a dictionary with the keys `name`, `age`, and `country`, then convert it into a DataFrame containing three rows of data.

In [10]:
data = {
    "name": ["Dmitry", "Alice", "John"],
    "age": [21, 25, 30],
    "country": ["Russia", "USA", "Canada"]
}

user_data = pd.DataFrame(data)

user_data

     name  age country
0  Dmitry   21  Russia
1   Alice   25     USA
2    John   30  Canada

## Problem 8

> Display the shape of your DataFrame.

In [11]:
user_data.shape

(3, 3)

## Problem 9

> Display the column names of your DataFrame.

In [12]:
user_data.columns

Index(['name', 'age', 'country'], dtype='str')

## Problem 10

> Display the data type of every column in your DataFrame.

In [13]:
user_data.dtypes

name         str
age        int64
country      str
dtype: object

## Problem 11

> Create a Series and display the total number of elements it contains using a single attribute.

In [14]:
len_series = pd.Series([1000, 2000, 3000, 4000, 5000])
len_series.size

5

## Problem 12

> Display the first **2** rows of your DataFrame using the method that normally displays the first **5** rows.

In [18]:
sample_df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [24, 29, 22, 31, 27],
    "Department": ["HR", "IT", "Finance", "Marketing", "IT"],
    "Salary": [45000, 65000, 52000, 58000, 70000],
    "Experience": [2, 5, 1, 4, 6]
})
sample_df

      Name  Age Department  Salary  Experience
0    Alice   24         HR   45000           2
1      Bob   29         IT   65000           5
2  Charlie   22    Finance   52000           1
3    David   31  Marketing   58000           4
4     Emma   27         IT   70000           6

In [19]:
sample_df.head(2)

    Name  Age Department  Salary  Experience
0  Alice   24         HR   45000           2
1    Bob   29         IT   65000           5

## Problem 13

> Display the last **1** row of your DataFrame using the method that normally displays the last **5** rows.`m

In [17]:
sample_df.tail(1)

   Name  Age Department  Salary  Experience
4  Emma   27         IT   70000           6

## Problem 14

> Create a Series containing the Celsius temperatures: `0, 15, 22, 37, 100`.

In [20]:
temp_celsius=pd.Series([0, 15, 22, 37, 100])
temp_celsius

0      0
1     15
2     22
3     37
4    100
dtype: int64

## Problem 15

> Display a summary of your DataFrame showing the column data types, non-null values, and memory usage.

In [22]:
sample_df.dtypes

Name            str
Age           int64
Department      str
Salary        int64
Experience    int64
dtype: object

In [23]:
sample_df.notnull

<bound method DataFrame.notnull of       Name  Age Department  Salary  Experience
0    Alice   24         HR   45000           2
1      Bob   29         IT   65000           5
2  Charlie   22    Finance   52000           1
3    David   31  Marketing   58000           4
4     Emma   27         IT   70000           6>

In [24]:
sample_df.memory_usage

<bound method DataFrame.memory_usage of       Name  Age Department  Salary  Experience
0    Alice   24         HR   45000           2
1      Bob   29         IT   65000           5
2  Charlie   22    Finance   52000           1
3    David   31  Marketing   58000           4
4     Emma   27         IT   70000           6>